---
version: 2.1

description: Build and test rust projects

executors:
  docker:
    parameters:
      version:
        type: string
        default: "latest"
    docker:
      - image: library/rust:<<parameters.version>>

jobs:
  build:
    executor: docker
    parameters:
      version:
        type: string
        default: "latest"
      release:
        type: boolean
        default: false
    steps:
      - install_deps
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            if [ "<<parameters.release>>" == "true" ]; then
              cargo build --release
            else
              cargo build
            fi
  test:
    executor: docker
    parameters:
      version:
        type: string
        default: "latest"
    steps:
      - install_deps
      - checkout
      - setup_remote_docker
      - run: cargo test

commands:
  install_deps:
    steps:
      - run:
          name: Install deps
          command: |
            apt-get update
            apt-get install -y git
